### ISSUE TITLE
Get days, time, building, etc. of courses

### ISSUE THREAD

**Issue by lmy0125** [ewang2002/webreg_scraper#6]
Hi Wang, I was using your webreg_scraper and I found that it was not collecting the days, start time, end time and some other attributes in the output file. I would like to get them in the result, how can I do so? I tried to go through the code but I know nothing about Rust. It seems like the webweg wrapper is imported somehow into this repo and its functions(SearchRequestBuilder) are used to get those data. Could you guide me through this?

Thank you

**Comment by ewang2002** [comment]
@lmy0125 Hi, to clarify, you want to be able to get a list of all courses (including their time) offered for this term?

Keep in mind that the scraper only gathers the number of students enrolled/waitlisted in a section. It does not gather information about the times that each sections meet. That being said, the library, [webweg](https://github.com/ewang2002/webweg), itself _does_ support this functionality via the [`get_course_info` function](https://github.com/ewang2002/webweg/blob/b0d5445003ba8fdf6d64dfb21c4353736c1f3eb5/src/wrapper.rs#L879).

I have a sample program that does just this [here](https://github.com/ewang2002/Utilities/tree/master/wgtools). Just run
```
./wgtools --term WI23 --data sections --cookie
```
and paste in your cookies. 

---

The `SearchRequestBuilder` is used to _search_ for specific courses; think of this as the Advanced Search feature in WebReg. Like I said though, to get the full details for a course, you should use the `get_course_info` function.


---

Let me know if you need any more help!

**Comment by ewang2002** [comment]
Perhaps I should mention that the utility program I linked exports everything as a TSV file. The contents of this file will look something like:

```
subj_course_id	sec_code	sec_id	instructor	total_seats	meetings
...
CSE 8B	A01	101617	Miranda, Gregory Joseph	350	LE,MWF,10:00 - 10:50,WLH 2001|FI,2023-03-20,8:00 - 10:59,WLH 2001|DI,W,15:00 - 15:50,WLH 2001
...
```

**Comment by lmy0125** [comment]
Yes, I think this is what I am looking for. However, there are some errors when I tried to compile.
![Screen Shot 2023-01-08 at 11 08 16 PM](https://user-images.githubusercontent.com/50187300/211256219-7fa93522-e96c-4007-b048-6956ef4d2171.png)

**Comment by ewang2002** [comment]
Oh I know the issue. I haven't updated the utilities in a while — I'll update it tomorrow morning, if that's okay with you.

**Comment by lmy0125** [comment]
Yeah, sure. Just curious what are all these codes for? Are you a student in UCSD? I am impressed by the amount of work that you have done.

**Comment by ewang2002** [comment]
Not sure if you're referring to codes as in the code here, or what's in the TSV file.

In any case, the reason why I wrote this code was so I can have a cached list of all courses offered for this term. With this list, I'm able to do things like [find classrooms that are empty](https://github.com/AWaffleInc/rubot/blob/master/src/commands/ucsd/FreeRooms.ts). 

As for the WebReg library (webweg) itself, that was because I wanted a uniform way to interact with WebReg. Having a library like webweg allows me to reuse that code for any project that might require me to interact with WebReg. 

The scraper (this project) was essentially made as a response to UCSD CSE's department not giving me enrollment history data. You can find a more detailed description [here](https://github.com/ewang2002/UCSDHistEnrollData/blob/master/docs/background.md). 

To answer the question you had initially, yes I'm a third-year Math-CS student at UCSD. Presumably, you're a UCSD student as well, so perhaps we can meet up at some point!

**Comment by ewang2002** [comment]
@lmy0125 please get the latest version of that utility program (wgtools) and try compiling it again. It should compile now.

**Comment by lmy0125** [comment]
Sure! We can meet up some time in campus. Our team actually tried to accomplish something like what you are doing here when I took CSE 110, but we didn't came up with such an optimal solution. It's so great to see someone has accomplished that. I will try your code tomorrow. Good night.

**Comment by ewang2002** [comment]
Were you able to get the program working?

**Comment by lmy0125** [comment]
Yes! Everything works perfectly. Thank you. And I just sent you an email.

**Comment by ewang2002** [comment]
Perfect. And I saw your email and will respond soon.
